application: albertolorente
version: 1
runtime: php55
api_version: 1

handlers:
- url: /css
  static_dir: css 
  
- url: /js
  static_dir: js 
  
- url: /img
  static_dir: img 
  
- url: /
  script: index.php

- url: /(.+\.php)$
  script: \1
