application: albertolorente-1149
version: 1
runtime: php55
api_version: 1

handlers:
- url: /dist
  static_dir: dist 
  
- url: /css
  static_dir: css 
  
- url: /assets
  static_dir: assets 
  
- url: /img
  static_dir: img 
  
- url: /
  script: index.php

- url: /(.+\.php)$
  script: \1
